enc_dim: 64
enc_stride: 32
enc_win: 64
feature_dim: 64
hidden_dim: 256
kernel_size: 3
num_block: 5
num_layer: 7
num_spk: 2
initial_unfreeze_blocks: 3
stft_hop: 32
stft_win: 512
batch_size: 16
lr: 0.001
save_dir: "Data/checkPoints_newTraj_childBRIR/"
save_name: "mimo-enhancer-FinetuneClass-bab-ChildBRIR"
epochs: 100
Best_epoch:  "Data/checkPoints_newTraj_childBRIR/mimo-separate-ClassFinetune-Bab-ChildBRIR-finalepoch=69-val_loss=-9.92.ckpt"
training_file_path: "Data/csvs/EnhancementFinetuneClass_Train_Bab.csv"
validation_file_path: "Data/csvs/EnhancementFinetuneClass_Val_Bab.csv"
test_file_path: "Data/csvs/ClassroomTest_6k_noBabs_full_1m_myst_2.4s_newtraj.csv"